// src/lib/assets/components/Chat.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import Message from './Message.svelte';
    import { token } from '$lib/stores/auth';
    import axios from 'axios';
    import { get } from 'svelte/store';

    export let limit: number = 10;

    interface ChatMessage {
        message_id: string;
        user_id: string;
        username: string;
        content: string;
        timestamp: number;
    }

    let messages: ChatMessage[] = [];
    let socket: WebSocket;

    async function handleEdit(event: CustomEvent<{ id: string, message: string }>) {
        const { id, message } = event.detail;
        const newContent = prompt("Edit message:", message);
        if (newContent !== null && newContent !== message) {
            const $token = get(token);
            try {
                await axios.patch("/api/messages", {
                    message_id: id,
                    content: newContent
                }, {
                    headers: {
                        Authorization: `Bearer ${$token}`
                    }
                });
            } catch (err) {
                console.error("Error editing message:", err);
            }
        }
    }

    async function handleDelete(event: CustomEvent<{ id: string }>) {
        const { id } = event.detail;
        if (confirm("Are you sure you want to delete this message?")) {
            const $token = get(token);
            try {
                await axios.delete("/api/messages", {
                    data: { message_id: id },
                    headers: {
                        Authorization: `Bearer ${$token}`
                    }
                });
            } catch (err) {
                console.error("Error deleting message:", err);
            }
        }
    }

    onMount(() => {
        socket = new WebSocket("ws://localhost:8081/ws");

        socket.onopen = () => {
            console.log("WS connected");
        };

        socket.onmessage = (event) => {
            const data = JSON.parse(event.data);

            switch (data.type) {
                case "userMessage":
                    messages = [...messages, data.payload];
                    break;

                case "editMessage":
                    messages = messages.map(m =>
                        m.message_id === data.payload.message_id
                            ? { ...m, content: data.payload.content }
                            : m
                    );
                    break;

                case "deleteMessage":
                    messages = messages.filter(
                        m => m.message_id !== data.payload.message_id
                    );
                    break;
            }

            if (messages.length > limit) {
                messages = messages.slice(-limit);
            }
        };

        socket.onerror = (err) => {
            console.error("WebSocket error:", err);
        };

        socket.onclose = () => {
            console.log("WS disconnected");
        };
    });

    onDestroy(() => {
        socket?.close();
    });
</script>

<div class="chat">
    {#each messages as msg (msg.message_id)}
        <Message
                message={msg.content}
                id={msg.message_id}
                timestamp={msg.timestamp}
                on:edit={handleEdit}
                on:delete={handleDelete}
        />
    {/each}
</div>

// src/assets/components/Chat/index.tsx
import { useState, useEffect } from "react";
import axios from "axios";
import Message from "../Message/index.tsx";
import { useAuth } from "../../../authContext.tsx";

import styles from "./index.module.css";

const message_api_url = "/api/messages";

interface ChatMessage {
  message_id: string;
  user_id: string;
  username: string;
  content: string;
  timestamp: number;
}

interface ChatProps {
  limit?: number;
}

export default function Chat({ limit = 10 }: ChatProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const { token } = useAuth();

  useEffect(() => {
    if (!token) return;

    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    const wsUrl = `${protocol}//${window.location.host}/ws-proxy`;

    const socket = new WebSocket(wsUrl, [token]);

    socket.onopen = () => console.log("WS connected");

    socket.onmessage = (event: MessageEvent) => {
      const data = JSON.parse(event.data);

      setMessages((prevMessages) => {
        let updatedMessages = [...prevMessages];

        switch (data.type) {
          case "userMessage":
            updatedMessages.push(data.payload);
            break;
          case "editMessage":
            updatedMessages = updatedMessages.map((m) =>
              m.message_id === data.payload.message_id
                ? { ...m, content: data.payload.content }
                : m
            );
            break;
          case "deleteMessage":
            updatedMessages = updatedMessages.filter(
              (m) => m.message_id !== data.payload.message_id
            );
            break;
          default:
            break;
        }

        if (updatedMessages.length > limit) {
          return updatedMessages.slice(-limit);
        }
        return updatedMessages;
      });
    };

    socket.onerror = (err: Event) => console.error("WebSocket error:", err);
    socket.onclose = () => console.log("WS disconnected");

    return () => {
      socket.close();
    };
  }, [limit, token]);

  const handleEdit = async (id: string, message: string) => {
    const newContent = prompt("Edit message:", message);
    if (newContent !== null && newContent !== message) {
      try {
        await axios.patch(
          message_api_url,
          {
            message_id: id,
            content: newContent,
          },
          {
            headers: { Authorization: `Bearer ${token}` },
          }
        );
      } catch (err) {
        console.error("Error editing message:", err);
      }
    }
  };

  const handleDelete = async (id: string) => {
    if (window.confirm("Are you sure you want to delete this message?")) {
      try {
        await axios.delete(message_api_url, {
          data: { message_id: id },
          headers: { Authorization: `Bearer ${token}` },
        });
      } catch (err) {
        console.error("Error deleting message:", err);
      }
    }
  };

  return (
    <div className={styles.chat}>
      {messages.map((msg) => (
        <Message
          key={msg.message_id}
          id={msg.message_id}
          username={msg.username}
          message={msg.content}
          timestamp={msg.timestamp}
          onEdit={handleEdit}
          onDelete={handleDelete}
        />
      ))}
    </div>
  );
}
