// src/lib/assets/components/Input.svelte
<script lang="ts">
    import Message from "$lib/assets/components/Message.svelte";
    import axios from "axios";

    type ChatMessage = {
        id: number;
        text: string;
        fromMe: boolean;
    }

    import { token } from '$lib/stores/auth';
    import { get } from 'svelte/store';

    function sendMessage(content: string){
        const $token = get(token);
        axios.post("/api/messages", {
           content: content,
        }, {
            headers: {
                Authorization: `Bearer ${$token}`
            }
        })

        message = "";
    }

    let message: string = "";
    let messages: ChatMessage[] = [];

</script>

<div class="chat">
    {#each messages as msg (msg.id)}
        <Message message={msg.text} fromMe={true} id=0 />
    {/each}
</div>

<div class="main">
    <input
            type="text"
            placeholder="Enter message..."
            bind:value={message}
            on:keyup={(e) => e.key === "Enter" && sendMessage(message)}>

</div>

<style>
    @import '../styles/input.scss';
</style>

// src/assets/components/Input.tsx
import React, { useState } from 'react';
import axios from 'axios';
import { useAuth } from '../../authContext.tsx';

import '../styles/input.scss'

export default function Input() {
    const [message, setMessage] = useState<string>("");
    const { token } = useAuth();

    const sendMessage = async () => {
        if (!message.trim()) return;

        try {
            await axios.post("/api/messages", {
                content: message,
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
            setMessage("");
        } catch (err) {
            console.error(err);
        }
    };

    return (
        <div className="main">
            <input
                type="text"
                placeholder="Enter message..."
                value={message}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setMessage(e.target.value)}
                onKeyUp={(e: React.KeyboardEvent<HTMLInputElement>) => e.key === "Enter" && sendMessage()}
            />
        </div>
    );
}
