// src/components/Login.tsx
import React, { useState } from "react";
import {useAuth} from "../authContext.tsx";

import '../assets/styles/login.scss'

interface LoginResponse {
    token: string;
}

export default function Login() {
    const [username, setUsername] = useState<string>("");
    const { setToken } = useAuth();

    const login = async () => {
        console.log(username);
        try {
            const res = await fetch('http://localhost:8080/login', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ username }),
            });

            if (!res.ok) throw new Error("Login failed.");

            const data: LoginResponse = await res.json();
            setToken(data.token);
            console.log("JTW: ", data.token);
        } catch (error) {
            console.log(error);
        }
    }

    return (
        <div className="login-card">
            <h2>Log in</h2>
            <input
                placeholder="Username"
                className="login-input"
                value={username}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}
            />
            <button id="login-button" onClick={login} className="button">Log in</button>
        </div>
    )
}

// src/lib/assets/components/Login.svelte
<script>
    import { onMount } from "svelte";
    import { token } from "$lib/stores/auth.js";

    let username = "";

    onMount(() => {
        if (!document.cookie.includes('id=')){
            document.cookie = `id=${Math.floor(Math.random() * 1000000)}; path=/; max-age=86400`;
        }
    });

    async function login() {
      console.log(username)
      const res = await fetch('http://localhost:8080/login', {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username }),
      }).then(res => {
        if (!res.ok) throw new Error("login failed");
        return res.json();
      }).then(data => {
        token.set(data.token);
        console.log("JWT:", data.token)
      }).catch(err => {
        console.error(err);
      })
    }
</script>

<div class="login-card">
    <h2>Log In</h2>
    <input placeholder="Username" class="input" bind:value={username} />
    <!-- <input placeholder="Password" type="password" class="input" /> -->
    <button id="login" class="button" on:click={login}>Log In</button>
</div>

<style>
    @import '../styles/login.scss';
</style>
